title: Jingru Liu's Homepage
page-top-title: Jingru Liu(刘静茹)
top-section-bg-text: Aircraft Design and Engineering
home-subtitle:  Jingru Liu&ensp;|&ensp;刘静茹
copyright-text: '&copy; Jingru Liu2023-2024. All Rights Reserved.'
